### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by mderazon** [mvila/validate-email-hostname#4]
when using in node

```
ReferenceError: regeneratorRuntime is not defined
    at /home/me/disposable-email-domains/node_modules/validate-email-hostname/lib/index.js:9:31
    at Object.<anonymous> (/home/me/disposable-email-domains/node_modules/validate-email-hostname/lib/index.js:78:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/me/disposable-email-domains/test/index.js:2:16)
    at Module._compile (module.js:409:26)
```

Missing babel-polyfill ?
http://stackoverflow.com/questions/28976748/regeneratorruntime-is-not-defined

**Comment by mvila** [comment]
Yes, you must `require('babel-polyfill')` before using this module.
